### ISSUE TITLE
大佬有个问题，关于config中的sensor2ego_rotation的疑问

### ISSUE THREAD

**Issue by zouzouwei** [linClubs/BEVDet-ROS-TensorRT#1]
我理解的4D引入多帧融合这个特征，其中使用的就是当前时刻自车的旋转与平移，也就是需要实时更新ego2global_rot，ego2global_trans的状态，但是我看代码中cam_data.param.ego2global_rot直接从config中取的，然后ros读取的topic也只有六路相机数据，就疑惑ego2global_rot、ego2global_trans怎么更新的。麻烦大佬了

**Comment by linClubs** [comment]
这里没有进行多帧的特征融合。只用了当前帧的参数。

具体参数值只加载了这4个。都是当前帧时刻的参数： T_lidar2cam, 内参K_cam, T_lidar2img, img_aug_matrix 。

详细参考[bevfusion_plugin.cpp](https://github.com/linClubs/BEVFusion-ROS-TensorRT/blob/main/src_ros/bevfusion_plugin.cpp)中的BEVFusionNode::BEVFusionNode(const std::string& model_name, const std::string& precision)函数内容：

~~~c
...
  camera2lidar = nv::Tensor::load(config_path + "/camera2lidar.tensor", false);
  camera_intrinsics = nv::Tensor::load(config_path + "/camera_intrinsics.tensor", false);
  lidar2image = nv::Tensor::load(config_path + "/lidar2image.tensor", false);
  img_aug_matrix = nv::Tensor::load(config_path + "/img_aug_matrix.tensor", false);
....
~~~

**Comment by zouzouwei** [comment]
`    // [STEP 4] : align BEV feature

    if(use_adj){
        GetAdjFrameFeature(cam_data.param.scene_token, cam_data.param.ego2global_rot, 
                        cam_data.param.ego2global_trans, (float*)bevstage_buffer[bevbuffer_map["BEV_feat"]]);
        CHECK_CUDA(cudaDeviceSynchronize());
    }
    auto align_feat_end = high_resolution_clock::now()`
可是这一步不是进行多帧融合吗，融合九帧bev的特征shape是1x720x180x180，然后我就很疑惑它的ego2global_rot 跟ego2global_trans好像用的都是config中给的固定值，难道不需要实时更新么。

**Comment by linClubs** [comment]
sorry前面我看错了。这里是需要ego2global参数，工程中连续检测时代码中一直用的第一帧的参数ego2global值，应该不影响检测结果，相当车不动做检测，可不可这样理解？
还有融合前后帧，这个前后帧姿态变化不大，应该对可视化结果影响不大，图像上框边缘不准，可能map会下降。

后期可以融合slam估计一下里程计信息，解决这个参数问题，但是考虑算力问题；还可以用imu和gps估计一个里程计；也可以单独用imu做前后帧的相对姿态估计。

**Comment by persuelx** [comment]
@linClubs  你好，请问参数配置文件下一共有两个不同意义的参数 ego2global_rotation，这两种参数分别代码啥意义？按理说车身到全局坐标系的旋转 这几个参数应该是一样的(不过配置文件中也差别不是很大。)
