### ISSUE TITLE
大佬，想请教您一下为什么我跑出来的RViz上并没有对应的3D目标检测框

### ISSUE THREAD

**Issue by yuezhao1** [linClubs/BEVDet-ROS-TensorRT#2]
大佬，想请教您一下。我在使用您的流程，先进行source devel/setup.bash使工作空间生效，然后运行roslaunch bevdet bevdet_node.launch之后，进行数据集的播放rosbag play nus.bag。
但是在RViz中，并不能框出模型检测的结果，图片上没有框，雷达上貌似有一堆框挤在了一起，请问这是什么原因导致的呢？是因为我没有放camera2lidar.tensor，camera_intrinsics.tensor，lidar2image.tensor，img_aug_matrix.tensor这些内外参吗？导致投影不到对应的位置导致的吗？
![image](https://github.com/linClubs/BEVDet-ROS-TensorRT/assets/49402805/6ee4c5a1-0ddf-4088-97eb-e0a5cd1cf542)
我看日志输出中对应的模型是有检测出目标的
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 6.140 ms
[Image stage  ] cost time: 55.082 ms
[BEV pool     ] cost time: 1.578 ms
[Align Feature] cost time: 11.676 ms
[BEV stage    ] cost time: 27.782 ms
[Postprocess  ] cost time: 4.111 ms
[Infer total  ] cost time: 106.370 ms
Detect 182 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 8.128 ms
[Image stage  ] cost time: 55.300 ms
[BEV pool     ] cost time: 1.558 ms
[Align Feature] cost time: 4.230 ms
[BEV stage    ] cost time: 25.304 ms
[Postprocess  ] cost time: 6.083 ms
[Infer total  ] cost time: 100.603 ms
Detect 182 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 6.588 ms
[Image stage  ] cost time: 55.931 ms
[BEV pool     ] cost time: 1.577 ms
[Align Feature] cost time: 4.005 ms
[BEV stage    ] cost time: 32.851 ms
[Postprocess  ] cost time: 2.851 ms
[Infer total  ] cost time: 103.802 ms
Detect 182 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 7.425 ms
[Image stage  ] cost time: 60.200 ms
[BEV pool     ] cost time: 1.565 ms
[Align Feature] cost time: 3.511 ms
[BEV stage    ] cost time: 22.413 ms
[Postprocess  ] cost time: 1.963 ms
[Infer total  ] cost time: 97.077 ms
Detect 181 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 7.795 ms
[Image stage  ] cost time: 53.653 ms
[BEV pool     ] cost time: 3.795 ms
[Align Feature] cost time: 9.922 ms
[BEV stage    ] cost time: 21.143 ms
[Postprocess  ] cost time: 3.801 ms
[Infer total  ] cost time: 100.109 ms
Detect 181 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 10.178 ms
[Image stage  ] cost time: 55.276 ms
[BEV pool     ] cost time: 1.573 ms
[Align Feature] cost time: 5.030 ms
[BEV stage    ] cost time: 26.030 ms
[Postprocess  ] cost time: 8.240 ms
[Infer total  ] cost time: 106.328 ms
Detect 181 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 6.173 ms
[Image stage  ] cost time: 58.563 ms
[BEV pool     ] cost time: 1.871 ms
[Align Feature] cost time: 11.229 ms
[BEV stage    ] cost time: 26.205 ms
[Postprocess  ] cost time: 1.808 ms
[Infer total  ] cost time: 105.850 ms
Detect 182 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 10.167 ms
[Image stage  ] cost time: 60.363 ms
[BEV pool     ] cost time: 1.603 ms
[Align Feature] cost time: 7.021 ms
[BEV stage    ] cost time: 21.761 ms
[Postprocess  ] cost time: 5.156 ms
[Infer total  ] cost time: 106.071 ms
Detect 181 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
-------------------0-------------------
scenes_token : e7ef871f77f44331aefdebc24ec034b7, timestamp : 1533201470448696
[Preprocess   ] cost time: 6.765 ms
[Image stage  ] cost time: 57.314 ms
[BEV pool     ] cost time: 1.686 ms
[Align Feature] cost time: 11.037 ms
[BEV stage    ] cost time: 26.437 ms
[Postprocess  ] cost time: 5.277 ms
[Infer total  ] cost time: 108.516 ms
Detect 181 objects
Failed to decompress jpeg: Wrong JPEG library version: library is %d, caller expects %d
但是RViz上并没有框。
而且我发现我的scenes_token和timestamp都是同一组数字，这是我没有把nus.bag输入进去吗？一直输入的是其中的一帧吗？

数据：使用您提供的nus.bag数据包
模型：使用您提供的onnx文件转换成对应的bev_stage_lt_d.engine和img_stage_lt_d.engine文件

麻烦大佬了

**Comment by yuezhao1** [comment]
我看在BEVDet-ROS-TensorRT的samole0中的samole0000.yaml中好像是存放了相机之间的内参以及相机的平移旋转矩阵等，是我需要修改什么地方，内参没有加载上吗？还是因为什么？麻烦大佬了

**Comment by yuezhao1** [comment]
我看在BEVDet-ROS-TensorRT的samole0中的samole0000.yaml中好像是存放了相机之间的内参以及相机的平移旋转矩阵等，是我需要修改什么地方，内参没有加载上吗？还是因为什么？麻烦大佬了

**Comment by linClubs** [comment]
可以打印ros消息看看是否有box的消息，检查一下

**Comment by yuezhao1** [comment]
嗯嗯，已经解决了 @linClubs 谢谢~

**Comment by SimLuo2014** [comment]
> 嗯嗯，已经解决了 @linClubs 谢谢~

@yuezhao1 我也遇到了这种问题，请问大佬是怎么解决的？
